server:
  port: 8101
  tomcat:
    uri-encoding: UTF-8
    max-threads: 5000
    max-connections: 10000

spring:
  datasource:
    url: jdbc:mysql://47.115.147.28:3306/ballvideo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: laiyudan
    password: qEuW1Kdaw0h8FZqA
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 120000
      maximumPoolSize: 2500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  seconddatasource:
    url: jdbc:mysql://47.115.147.28:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: laiyudan
    password: qEuW1Kdaw0h8FZqA
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  thirdDataSource:
    url: jdbc:mysql://rm-wz9r3k68fq34ck17noo.mysql.rds.aliyuncs.com:3306/shangbao?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: shangbao_java
    password: v1pXDjTlUKoUnaTv
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  fourthDatasource:
    url: jdbc:mysql://rm-wz9r3k68fq34ck17noo.mysql.rds.aliyuncs.com:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xy_java
    password: 49HUwMKoeVC1qQpV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    #host: 120.78.185.45 外网地址
    host: 120.78.185.45
    port: 6379
    password: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    database: 4
    timeout: 15000
    jedis:
      pool:
      max-active: 10000
      max-idle: 200
      min-idle: 50
      max-wait: 3000
    shangbaoDatabase: 1
    shangbaoHost: 47.112.149.132
    shangbaoPort: 6379
    shangbaoPassword: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    shangbaoTimeOut: 15000
  session:
    store-type: redis
  data:
    elasticsearch:
      cluster-name: ballVideo
      cluster-nodes: 47.112.149.108:9300
#MQ管理后台外网地址：http://47.112.141.18:15672/#/exchanges
  rabbitmq:
    addresses: 47.112.141.18
    username: xiyou
    port: 5672
    password: REl1QCkkvpGICzSo
    open: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:log4j2/Log4j2-onProd.xml

